### ISSUE TITLE
Crash when using RMC on Mac

### ISSUE THREAD

**Issue by markusstephanides** [TriAxis-Games/RuntimeMeshComponent#173]
Hello! 

I'm currently having the same issue as [this user](https://github.com/Koderz/RuntimeMeshComponent/issues/119).

My project with RMC works perfectly on Windows and it compiles without issues on Mac. But when I run it on Mac and the Mesh is being created with RMC the game crashes.

Crash during debug:
![Screen1](https://user-images.githubusercontent.com/6057570/82725333-91bc5b00-9cdc-11ea-8d69-38a36544c04f.png)

Crash without debugging:
![Screen2](https://user-images.githubusercontent.com/6057570/82725344-9da81d00-9cdc-11ea-91f4-32add93f53c5.png)

**Comment by Koderz** [comment]
I'm curious if this is still an issue? Does this still happen in the current version?

Unfortunately there's not enough information in that exception and stacktrace to see what's causing it to complain.

**Comment by markusstephanides** [comment]
I will check with the newest version and let you know!

**Comment by Koderz** [comment]
I'm not aware of this still being an issue and as I haven't heard from you in a while I'll be closing this issue.  If this problem or another persists please feel free to reopen or submit a new report!

-Chris
