### ISSUE TITLE
Crashed on Android: RHITransferVertexBufferUnderlyingResource isn't implemented for the current RHI

### ISSUE THREAD

**Issue by YuCrazing** [TriAxis-Games/RuntimeMeshComponent#189]
Hey!

I have a crash problem when using RMC on Xiaomi6  (`Android, OpenGL ES 3.2`), the log shows "`RHITransferVertexBufferUnderlyingResource isn't implemented for the current RHI`". Anyone can solve this problem?

The complete log is shown below:

> 
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: === Critical error: ===
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error:
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: Fatal error: [File:C:/Projects_quick/MorefunUE4-Origin/Engine/Source/Runtime/RHI/Private/DynamicRHI.cpp] [Line: 353]
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: RHITransferVertexBufferUnderlyingResource isn't implemented for the current RHI
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C0EBCADC libUE4.so(0x000000000A4A1ADC)!void FMsg::Logf_Internal<char16_t [80]>(char const*, int, FName const&, ELogVerbosity::Type, char16_t const (&) [80])  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C307886C libUE4.so(0x000000000C65D86C)!\[Unknown]()  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C3078764 libUE4.so(0x000000000C65D764)!FDynamicRHI::RHITransferVertexBufferUnderlyingResource(FRHIVertexBuffer*, FRHIVertexBuffer*)  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C3094FE4 libUE4.so(0x000000000C679FE4)!FRHICommandUpdateRHIResources::Execute(FRHICommandListBase&)  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C30D2CF8 libUE4.so(0x000000000C6B7CF8)!FRHICommand<FRHICommandUpdateRHIResources, FRHICommandUpdateRHIResourcesString2106>::ExecuteAndDestruct(FRHICommandListBase&, FRHICommandListDebugContext&)  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C3095CF8 libUE4.so(0x000000000C67ACF8)!FRHICommandListExecutor::ExecuteInner_DoExecute(FRHICommandListBase&)  []
> LogPlayLevel: Error:   08-19 15:00:40.524 20820 21022 D UE4     : [2020.08.19-07.00.40:524][124]LogAndroid: Error: [Callstack] 0x00000000C31231FC libUE4.so(0x000000000C7081FC)!FExecuteRHIThreadTask::DoTask(ENamedThreads::Type, TRefCountPtr<FGraphEvent> const&)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C3122FC4 libUE4.so(0x000000000C707FC4)!TGraphTask<FExecuteRHIThreadTask>::ExecuteTask(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1A223EC libUE4.so(0x000000000B0073EC)!FBaseGraphTask::Execute(TArray<FBaseGraphTask*, TSizedDefaultAllocator<32> >&, ENamedThreads::Type)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1A234D0 libUE4.so(0x000000000B0084D0)!FNamedTaskThread::ProcessTasksNamedThread(int, bool)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1A22A24 libUE4.so(0x000000000B007A24)!FNamedTaskThread::ProcessTasksUntilQuit(int)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1A20CDC libUE4.so(0x000000000B005CDC)!FTaskGraphImplementation::ProcessThreadUntilRequestReturn(ENamedThreads::Type)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C31C1A54 libUE4.so(0x000000000C7A6A54)!FRHIThread::Run()  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1B57B58 libUE4.so(0x000000000B13CB58)!FRunnableThreadPThread::Run()  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000C1A1F284 libUE4.so(0x000000000B004284)!FRunnableThreadPThread::_ThreadProc(void*)  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000ECD647F2 libc.so(0x00000000000717F2)!\[Unknown]()  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error: [Callstack] 0x00000000ECD10FD2 libc.so(0x000000000001DFD2)!\[Unknown]()  []
> LogPlayLevel: Error:   08-19 15:00:40.525 20820 21022 D UE4     : [2020.08.19-07.00.40:525][124]LogAndroid: Error:

**Comment by Koderz** [comment]
Hey @YuCrazing 

Does this still happen in the current master branch version?

**Comment by DigiKrafting** [comment]
I too received the same error on Android from the marketplace version, I just tried from github current master branch and the plugin worked without any errors. * I had to comment out all "RMC_LOG_VERBOSE" references to compile for Android but that would be a separate issue.

**Comment by Koderz** [comment]
@DigiKrafting  What was the error with the logging? I'll try to fix that in master before I tag a new version to go to the MP tomorrow.

**Comment by DigiKrafting** [comment]
@Koderz Here is the error I get when compiling for Android: `UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     C:/Users/kye/Documents/Unreal Projects/MeshComponent/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Private/Providers/RuntimeMeshProviderStatic.cpp(15,2): error: expected expression
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):             RMC_LOG_VERBOSE("Created");
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):             ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     C:/Users/kye/Documents/Unreal Projects/MeshComponent/Plugins/RuntimeMeshComponent/Source/RuntimeMeshComponent/Private/Providers/RuntimeMeshProviderStatic.cpp(8,2): note: expanded from macro 'RMC_LOG_VERBOSE'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):             UE_LOG(RuntimeMeshLog2, Verbose, TEXT("[RMPS:%d Thread:%d]: " Format), GetUniqueID(), FPlatformTLS::GetCurrentThreadId(), __VA_ARGS__);
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):             ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):     C:/UnrealEngine/4.25.3/Engine/Source/Runtime/Core/Public\Logging//LogMacros.h(214,63): note: expanded from macro 'UE_LOG'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):                                     UE_LOG_noinline_lambda(CategoryName, Format, ##__VA_ARGS__); \`

* It compiles without errors on a Win64 shipping build.

**Comment by DigiKrafting** [comment]
@Koderz Just tried with launcher version 4.25.3 and get the same logging macro error when compiling for Android

**Comment by DigiKrafting** [comment]
@Koderz

1>PLATFORM_ANDROID_NDK_VERSION = 210200
1>NDK toolchain: r21b, NDK version: 29, GccVersion: 4.9, ClangVersion: 9.0.8

**Comment by DigiKrafting** [comment]
@Koderz
[MeshComponent.log](https://github.com/KoderzUnreal/RuntimeMeshComponent/files/5146518/MeshComponent.log)

**Comment by venomkiss** [comment]
From what I can gather, the android compilation issue regarding logging macros is due essentially to extraneous commas being introduced where __VA_ARGS__ expands to an empty string in the various RMC_LOG_VERBOSE definitions. The standard GCC fix is to use the token paste operator to tell the preprocessor to remove said commas. Changing __VA_ARGS__ to ##__VA_ARGS__ in the following source files will fix it:

RuntimeMeshProviderStatic.cpp : line 9
RuntimeMeshComponentProxy.cpp : line 23
RuntimeMeshProxy.cpp : line 19
RuntimeMeshStaticMeshConverter.cpp : line 15
RuntimeMesh.cpp : line 27
RuntimeMeshRendering.h : line 654

**Comment by Koderz** [comment]
I believe this should all be fixed as of now in the latest version.

-Chris
