### ISSUE TITLE
The parameters in CopyStaticMeshToRuntimeMesh function

### ISSUE THREAD

**Issue by universewill** [TriAxis-Games/RuntimeMeshComponent#205]
How to convert staticmesh to runtimemesh?
I can't find document about it.

I found the function 'CopyStaticMeshToRuntimeMesh', but don't understand the meaning of the parameter:int32 CollisionLODIndex = -1, int32 MaxLODToCopy = 8

Is it just ok to leave these two parameters to default value?

**Comment by Moddingear** [comment]
CollisionLODIndex is the index to use to generate the complex collision mesh and MaxLODToCopy is the maximum LOD index to copy to the RMC. if you only want the high poly version set this to 1.
