### ISSUE TITLE
Cant compile  on ue5 early access

### ISSUE THREAD

**Issue by fluffy-git** [TriAxis-Games/RuntimeMeshComponent#218]
Log:

[MyProject.log](https://github.com/TriAxis-Games/RuntimeMeshComponent/files/6677821/MyProject.log)

**Comment by mozg4D** [comment]
try:
RuntimeMeshComponent/Source/RuntimeMeshComponent/Private/RuntimeMeshComponentProxy.cpp(111):
replace 'bOpaqueRelevance' with 'Result.bOpaque' or remove this part

**Comment by Jaydanson** [comment]
Didnt work for me :(

**Comment by andersoje2** [comment]
Use the drop down "master" button and select ue5
