### ISSUE TITLE
UE5.0.3 use this plugin cannot build

### ISSUE THREAD

**Issue by NierAimer** [TriAxis-Games/RuntimeMeshComponent#233]
RuntimeMeshComponentDetails.cpp(162): [C2248] 'UStaticMesh::LightingGuid': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(1106): [C2248] see declaration of 'UStaticMesh::LightingGuid'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(165): [C2248] 'UStaticMesh::StaticMaterials': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(843): [C2248] see declaration of 'UStaticMesh::StaticMaterials'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(213): [C2664] 'int TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add(UE::Math::TVector<float> &&)': cannot convert argument 1 from 'const FVector' to 'UE::Math::TVector<float> &&'
  RuntimeMeshComponentDetails.cpp(213): [C2664] Reason: cannot convert from 'const FVector' to 'UE::Math::TVector<float>'
  RuntimeMeshComponentDetails.cpp(213): [C2664] No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  Array.h(2027): [C2664] see declaration of 'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add'
  RuntimeMeshComponentDetails.cpp(225): [C2664] 'int TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add(UE::Math::TVector<float> &&)': cannot convert argument 1 from 'FVector' to 'UE::Math::TVector<float> &&'
  RuntimeMeshComponentDetails.cpp(225): [C2664] Reason: cannot convert from 'FVector' to 'UE::Math::TVector<float>'
  RuntimeMeshComponentDetails.cpp(225): [C2664] No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  Array.h(2027): [C2664] see declaration of 'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add'
  RuntimeMeshComponentDetails.cpp(226): [C2664] 'int TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add(UE::Math::TVector<float> &&)': cannot convert argument 1 from 'FVector' to 'UE::Math::TVector<float> &&'
  RuntimeMeshComponentDetails.cpp(226): [C2664] Reason: cannot convert from 'FVector' to 'UE::Math::TVector<float>'
  RuntimeMeshComponentDetails.cpp(226): [C2664] No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  Array.h(2027): [C2664] see declaration of 'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add'
  RuntimeMeshComponentDetails.cpp(227): [C2664] 'int TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add(UE::Math::TVector<float> &&)': cannot convert argument 1 from 'FVector' to 'UE::Math::TVector<float> &&'
  RuntimeMeshComponentDetails.cpp(227): [C2664] Reason: cannot convert from 'FVector' to 'UE::Math::TVector<float>'
  RuntimeMeshComponentDetails.cpp(227): [C2664] No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  Array.h(2027): [C2664] see declaration of 'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add'
  RuntimeMeshComponentDetails.cpp(231): [C2664] 'int TArray<UE::Math::TVector2<float>,FDefaultAllocator>::Add(UE::Math::TVector2<float> &&)': cannot convert argument 1 from 'const FVector2D' to 'UE::Math::TVector2<float> &&'
  RuntimeMeshComponentDetails.cpp(231): [C2664] Reason: cannot convert from 'const FVector2D' to 'UE::Math::TVector2<float>'
  RuntimeMeshComponentDetails.cpp(231): [C2664] No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
  Array.h(2027): [C2664] see declaration of 'TArray<UE::Math::TVector2<float>,FDefaultAllocator>::Add'
  RuntimeMeshComponentDetails.cpp(265): [C2248] 'UStaticMesh::SourceModels': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(629): [C2248] see declaration of 'UStaticMesh::SourceModels'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(280): [C2248] 'UStaticMesh::StaticMaterials': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(843): [C2248] see declaration of 'UStaticMesh::StaticMaterials'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(288): [C2248] 'UStaticMesh::SectionInfoMap': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(647): [C2248] see declaration of 'UStaticMesh::SectionInfoMap'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(300): [C2248] 'UStaticMesh::StaticMaterials': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(843): [C2248] see declaration of 'UStaticMesh::StaticMaterials'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshComponentDetails.cpp(304): [C2248] 'UStaticMesh::BodySetup': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(963): [C2248] see declaration of 'UStaticMesh::BodySetup'
  MorphTarget.h(17): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshProviderStaticMesh.cpp(120): [C2248] 'UStaticMesh::RenderData': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(607): [C2248] see declaration of 'UStaticMesh::RenderData'
  RuntimeMeshProviderStaticMesh.generated.h(11): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshProviderStaticMesh.cpp(128): [C2248] 'UStaticMesh::StaticMaterials': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(843): [C2248] see declaration of 'UStaticMesh::StaticMaterials'
  RuntimeMeshProviderStaticMesh.generated.h(11): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshProviderStaticMesh.cpp(134): [C2248] 'UStaticMesh::RenderData': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(607): [C2248] see declaration of 'UStaticMesh::RenderData'
  RuntimeMeshProviderStaticMesh.generated.h(11): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshProviderStaticMesh.cpp(141): [C2248] 'UStaticMesh::RenderData': cannot access private member declared in class 'UStaticMesh'
  StaticMesh.h(607): [C2248] see declaration of 'UStaticMesh::RenderData'
  RuntimeMeshProviderStaticMesh.generated.h(11): [C2248] see declaration of 'UStaticMesh'
  RuntimeMeshRendering.h(603): [C2512] 'FRHIResourceCreateInfo': no appropriate default constructor available
  RHICommandList.h(52): [C2512] see declaration of 'FRHIResourceCreateInfo'
  RuntimeMesh.cpp(547): [C2679] binary '=': no operator found which takes a right-hand operand of type 'TArray<FVector,FDefaultAllocator>' (or there is no acceptable conversion)
  Array.h(590): [C2679] could be 'TArray<UE::Math::TVector<float>,FDefaultAllocator> &TArray<UE::Math::TVector<float>,FDefaultAllocator>::operator =(TArray<UE::Math::TVector<float>,FDefaultAllocator> &&)'
  Array.h(442): [C2679] or       'TArray<UE::Math::TVector<float>,FDefaultAllocator> &TArray<UE::Math::TVector<float>,FDefaultAllocator>::operator =(const TArray<UE::Math::TVector<float>,FDefaultAllocator> &)'
  Array.h(410): [C2679] or       'TArray<UE::Math::TVector<float>,FDefaultAllocator> &TArray<UE::Math::TVector<float>,FDefaultAllocator>::operator =(std::initializer_list<InElementType>)'
  RuntimeMesh.cpp(547): [C2679] while trying to match the argument list '(TArray<UE::Math::TVector<float>,FDefaultAllocator>, TArray<FVector,FDefaultAllocator>)'
  RuntimeMeshActor.cpp(16): [C2248] 'AActor::bCanBeDamaged': cannot access private member declared in class 'AActor'
  Actor.h(333): [C2248] see declaration of 'AActor::bCanBeDamaged'
  ContentStreaming.h(34): [C2248] see declaration of 'AActor'
  RuntimeMeshComponentProxy.cpp(9): [C1083] Cannot open include file: 'TessellationRendering.h': No such file or directory
  Microsoft.MakeFile.targets(45, 5): [MSB3073] The command ""C:\Program Files\Epic Games\UE_5.0\Engine\Build\BatchFiles\Build.bat" MenZiQuEditor Win64 Development -Project="D:\ue4Project\MenZiQuMAP\MenZiQu.uproject" -WaitMutex -FromMsBuild" exited with code 6.

**Comment by Moddingear** [comment]
Use branch RMC4_UE5 or RMC4.5-dev. UE5 isn't supported by Koderz but by the Community.
