### ISSUE TITLE
UE5.1 not compiling

### ISSUE THREAD

**Issue by BigBadWouf** [TriAxis-Games/RuntimeMeshComponent#238]
Create new c++ project in UE 5.1

Clone the git hub in the plugins folder. Launch in VS.

Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Avertissement	C4996	'UE::Math::TVector2<double>::operator <': TVector2 comparison operators are deprecated. Use ComponentwiseAllLessThan. For componentwise min/max/abs, use TVector2::{Min,Max,GetAbs}, FMath::{Min,Max,Abs} compute something different. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Modifiers\RuntimeMeshModifierAdjacency.cpp	63	
Erreur	C2248	'UStaticMesh::RenderData' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	120	
Avertissement	C4996	'UStaticMesh::RenderData': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	120	
Erreur	C2248	'UStaticMesh::StaticMaterials' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	128	
Avertissement	C4996	'UStaticMesh::StaticMaterials': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	128	
Erreur	C2248	'UStaticMesh::RenderData' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	134	
Avertissement	C4996	'UStaticMesh::RenderData': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	134	
Erreur	C2248	'UStaticMesh::RenderData' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	141	
Avertissement	C4996	'UStaticMesh::RenderData': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	141	
Avertissement	C4996	'UObjectBaseUtility::IsPendingKill': IsPendingKill() should no longer be used. Use IsValid(Object), IsValidChecked(Object) or GetValid(Object) instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\Providers\RuntimeMeshProviderStaticMesh.cpp	112	
Erreur	C1083	Impossible d'ouvrir le fichier include : 'IPhysXCookingModule.h' : No such file or directory	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponent\Private\RuntimeMesh.cpp	7	
Avertissement		#include AssetRegistry/AssetRegistryModule.h instead of AssetRegistryModule.h	Voxel	C:\UE_5.1\Engine\Source\Runtime\AssetRegistry\Public\AssetRegistryModule.h	6	
Erreur	C2248	'UStaticMesh::LightingGuid' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	162	
Avertissement	C4996	'UStaticMesh::LightingGuid': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	162	
Erreur	C2248	'UStaticMesh::StaticMaterials' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	165	
Avertissement	C4996	'UStaticMesh::StaticMaterials': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	165	
Erreur	C2665	'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	213	
Erreur	C2665	'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	225	
Erreur	C2665	'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	226	
Erreur	C2665	'TArray<UE::Math::TVector<float>,FDefaultAllocator>::Add' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	227	
Erreur	C2665	'TArray<UE::Math::TVector2<float>,FDefaultAllocator>::Add' : aucune des 2 surcharges n'a pu convertir tous les types d'arguments	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	231	
Erreur	C2248	'UStaticMesh::SourceModels' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	265	
Avertissement	C4996	'UStaticMesh::SourceModels': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	265	
Erreur	C2248	'UStaticMesh::StaticMaterials' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	280	
Avertissement	C4996	'UStaticMesh::StaticMaterials': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	280	
Erreur	C2248	'UStaticMesh::SectionInfoMap' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	288	
Avertissement	C4996	'UStaticMesh::SectionInfoMap': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	288	
Erreur	C2248	'UStaticMesh::StaticMaterials' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	300	
Avertissement	C4996	'UStaticMesh::StaticMaterials': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	300	
Erreur	C2248	'UStaticMesh::BodySetup' : impossible d'accéder à private membre déclaré(e) dans la classe 'UStaticMesh'	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	304	
Avertissement	C4996	'UStaticMesh::BodySetup': This must be protected for async build, always use the accessors even internally. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.	Voxel	D:\UE Projects\Voxel\Plugins\RuntimeMeshComponent\Source\RuntimeMeshComponentEditor\Private\RuntimeMeshComponentDetails.cpp	304

**Comment by Moddingear** [comment]
Use branch RMC4.5-dev if you're on UE5.1. The other UE5 branch only goes up to 5.0
